# -*- coding: utf-8 -*-
"""day-1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oEnLUpFSDAmmpGn3WpF6-hhvvmcKyFAJ
"""

print("hello World!!!")
print("Hridoy Ratno!!")

num=23
print(num)

name ='''Hridoy Ratno'''
age=24
a=None
print("My name is : ",name)
print("My age is : ",age)
print(type(name))
print(type(age))
print(type(a))

a,b=1,2.0
sum=a+b
print(sum)

# error
a,b=1,"3.0"
Sum=a+float(b)  # convert str to float
print(Sum)

#Right
a,b="1","3.0"
Sum=a+b
print(Sum)

name=input("Enter any name : ")
print("My name is ",name)

name1=input()
print(name1)
multiple=float(input("Enter any number : "))
print("The value of multiple is ",multiple)
divider=int(input("Enter any name : "))
print("The value of divider is ",divider)

#practice : input square side and print area
length=float(input("Enter the length of Square : "))
area= length*length
print("The Area of Square is ",area)

# exponential operator(**)
h=int(input())
i=int(input())
Exponential= h**i
print("The valaue of Exponential equation is ",Exponential)