# -*- coding: utf-8 -*-
"""day_5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eLEhtVai1VecIotW5xQj4Jp4GJJm7kO5

## Loop  

-> used to repeat instructions

-> types of loop :
1. while
2. for
3. Nested loop

## while loop
-> syntex

 while condition : Some work
"""

while True:
    print("Hello World!!")  #its a infinite loop

count=1
while count<=5:
    print("Hello Hridoy!!")
    count +=1
print(count)

"""## Practice Question using while loop"""

#print number from 1 to 10

i=1
while i<=10:
    print(i)
    i +=1

#print number from 10 to 1
i=10
while i>=1:
    print(i)
    i -=1

#print the multiplication table of a number n

n=int(input("Enter a num : "))
i=1
while i<=10:
    #mul=n*i
    print(n,"*",i,"=",n*i)
    i +=1

"""## keywords
1. Break
2. Continue
"""

# break : finished the loop
i=1
while i<=10:
    print(i)
    if(i==4):
        break
    i += 1
print("End of Loop")

# continue : skip the iteration value
i=1
while i<=10:
    i += 1
    if(i==4):
        continue
    print(i)
print("End of Loop")

"""## for loop
->> used for sequential traversal

->> syntex :

for element in list: some work

"""

nums=[34,66,45,94,32,90]   #list
for num in nums:
    print(num)

print(type(num))   #Depend on last index element.
print(type(nums))

tup=(27.6,48.6,69.7,90.5,94.9,87.4,75.3,50.7,"hridoy",97)
for val in tup:
    print(val)
    print(type(val))

print(type(val))
print(type(tup))

#for loop for string
str="Hridoy Ratno"
for char in str:
    print(char)
else:
    print("End")

#Parctice Question
list =[1,4,9,16,25,36,49,64,81,100]
for square in list:
    print(square)

tup=(1, 4, 9, 16, 25, 36, 49, 64, 81, 100)
x=49
for value in tup:
    if(value==x):
        print("Number is found.")
    else:
        print("Number is not found.")

"""## range()
-> Returns a sequence of number.

-> start value by default 0

syntex : range(start?, stop, step?)

  ->> step means increament or decreament

  ->> "?" means optional

"""

seq= range(5)   # starting value by  default 0
print(seq[0])
print(seq[1])
print(seq[2])
print(seq[3])
print(seq[4])

# using loop for this seq
seq=range(10)  #10 is equal to stop condition
for i in seq:
    print(i)

#set starting value
seq=range(5,10)  #(start , end)
for i in seq:
    print(i)

seq=range(2,10,2)  #(start , end, step)
for i in seq:
    print(i)

#practice Question
for i in range(1,11):
    print(i)

for i in range(10,0,-1):
    print(i)

#multiplication Table
n=int(input("Enter a num : "))
for i in range(1,11):
    print( n, "*", i,"=",n*i)

#pass Statement  :: null statement
for i in range(5):
    pass     #Skip

print("Do not work range block")

